spring:
  profiles:
    active: default

  sleuth:
    sampler.percentage: 1.0
    log.json.enabled: true

  jpa:
    generate-ddl: true


info.id: ${spring.application.name}:${server.port}


server:
  port: ${PORT:0}


logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


endpoints.shutdown.enabled: true


eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    prefer-ip-address: true
    instance-id: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    lease-renewal-interval-in-seconds: 3

  client:
    region: default
    registry-fetch-interval-seconds: 5